### ISSUE TITLE
QUERY: plans

### ISSUE THREAD

**Issue by mrose17** [rmchndrng/healthvault-js-library#1]
hi. when do you think that you'd be ready for someone to start using the library? i would very much like to write a server that reads from healthvault and puts values into numerousapp.

thanks and good luck!

**Comment by rmchndrng** [comment]
Hi,

Not anytime soon. Still in the initial phase and a long long way to go. I will be definitely continue to work on in as and when I get the time. You can ignore the code present till now as I will be restructuring and simplifying the library very soon.

Thanks,
Ram

**Comment by mrose17** [comment]
many thanks! glad to hear that you are still working ont his. we really need more ways to get data in and out of HealthVault... a node.js library will be a very welcome edition!

**Comment by rmchndrng** [comment]
Your welcome, I am little bit new to Node.js So taking a little bit of time to get the thinking process in a non-blocking manner as I am mainly used to C# development. Will let you know as soon as I feel pretty confident with the library.

Thanks,
Ram
